name: vector_canvas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.4.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ramanujan:
    path: ../ramanujan
  game_engine:
    path: ../../f4b/game_engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
